### PR TITLE
replace evm accountI interface

### PR DESCRIPTION
**Pull request by 0xmetaofo**
## Description

Closes: #XXXX

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

* [ ] provided a link to the relevant issue or specification
* [ ] added a changelog entry to `CHANGELOG.md`
* [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
* [ ] updated the relevant documentation or specification
* [ ] reviewed "Files changed" and left comments if necessary
* [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

* [ ] confirmed all author checklist items have been addressed
* [ ] reviewed API design and naming
* [ ] reviewed documentation is accurate
* [ ] reviewed tests and test coverage
* [ ] manually tested (if applicable)

### CODE REVIEW

**Review by 0xmetaofo — COMMENTED** [review]
ok

**Review by fibonacciTeam — APPROVED** [review]
ok

**Comment by fibonacciTeam** [comment]
ok

**Review by China-Chris — APPROVED** [review]
Thank you for submitting

**Pull request merged**
